services:
  - type: web
    name: apnea-alert-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main_render.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.0
