services:
  - type: web
    name: apnea-alert-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_render.py
    envVars:
      - key: PORT
        fromGroup: null
    autoDeploy: true