services:
  - type: web
    name: apnea-alert-api
    env: python
    buildCommand: pip install --only-binary :all: -r backend/requirements.txt
    startCommand: python backend/main_render.py
    envVars:
      - key: PORT
        value: 8000
